name: publish

on:
  push:
    branches: [ main ]

env:
  PROJECT_PATH: 'Necroperator/Necroperator.csproj'
  DOTNET_VERSION: '9.0.x'

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }} --runtime win-x64

    - name: Build project
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore --runtime win-x64
  
    - name: Publish project
      run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: ${{ github.run_number }}

    - name: Bundle artifacts
      uses: csexton/release-asset-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pattern: |
          publish/*.dll
          publish/*.exe
        release-url: ${{ steps.create_release.outputs.upload_url }}
